import type { Metadata } from 'next'
//import { Inter } from 'next/font/google'
import '@/app/styles/globals.scss'
import Header from '@/components/Header/header'
import Footer from '@/components/Footer/footer'
import { ReduxProviders } from '@/store/provider'
import StyledComponentsRegistry from '@/utils/AntdRegistry'

//const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="vi" className="scroll-smooth">
      <ReduxProviders>
        <body>
          <StyledComponentsRegistry>
              <div className="main_layout">
                <Header />
                {children}
                <Footer />
              </div>
          </StyledComponentsRegistry>
        </body>
      </ReduxProviders>
    </html>
  )
}
