import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import '@/app/styles/globals.scss'
import Header from '@/components/Header/header'
import Footer from '@/components/Footer/footer'
import { ReduxProviders } from '@/store/provider'
import StyledComponentsRegistry from '@/utils/AntdRegistry'

const montserrat = Montserrat({ 
  subsets: ['latin', 'vietnamese'], 
  variable: '--font-montserrat' 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="vi" className={`${montserrat.variable} scroll-smooth`}>
      <ReduxProviders>
        <body>
          <StyledComponentsRegistry>
            <div className="main_layout">
              <Header />
              {children}
              <Footer />
            </div>
          </StyledComponentsRegistry>
        </body>
      </ReduxProviders>
    </html>
  )
}
